{
 "title": "ASP.NET Core | System overview",
 "description": "Basic measurements of request handling using data from prometheus-net middleware",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instances",
    "label": "Instances",
    "query": "label_values(http_requests_received_total, instance)"
   },
   {
    "name": "controllers",
    "label": "Controllers",
    "query": "label_values(http_requests_received_total{instance =~ \"$instances\"}, controller)"
   }
  ]
 },
 "panels": [
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Request duration (controller-handled requests only)",
   "type": "heatmap",
   "description": "Does NOT include requests that were not mapped to an ASP.NET Core controller!",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{instance =~ \"$instances\", controller =~ \"$controllers\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "All requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count[$__rate_interval])*60"
    }
   ]
  },
  {
   "title": "Cpu percentage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "system_runtime_cpu_usage" }
   ]
  },
  {
   "title": "Error rate by controller",
   "type": "timeseries",
   "description": "4xx and 5xx status codes",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller =~ \"$controllers\", code =~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[$__rate_interval])) by (controller, code)",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller = \"\", code =~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[$__rate_interval])) by (controller)",
     "legendFormat": "(None)"
    },
    {
     "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", code =~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[$__rate_interval])) by ( code)"
    }
   ]
  },
  {
   "title": "Total memory in bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 13 },
   "targets": [
    { "expr": "dotnet_total_memory_bytes" }
   ]
  },
  {
   "title": "Total req/s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller =~ \"$controllers\"}[3m]))"
    }
   ]
  },
  {
   "title": "In progress (global)",
   "type": "stat",
   "description": "Across ALL controllers globally!",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_in_progress{instance =~ \"$instances\"})"
    }
   ]
  },
  {
   "title": "Average request duration / per action",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": " sum by (action) (increase(http_request_duration_seconds_bucket{}[$__rate_interval])) "
    }
   ]
  },
  {
   "title": "Heap size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 18 },
   "targets": [
    { "expr": "system_runtime_gc_heap_size" }
   ]
  },
  {
   "title": "Current http connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 18 },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_http_connections_current_connections"
    }
   ]
  },
  {
   "title": "Requests received by controller",
   "type": "graph",
   "description": "Counts all requests, both successful and failed",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller =~ \"$controllers\"}[3m])) by (controller)",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller = \"\"}[3m]))",
     "legendFormat": "(None)"
    }
   ]
  }
 ]
}