version: '3.4'

services:
  elasticsearch:
    container_name: sample_crud_app_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - host
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - samplecrudaspnet-data:/usr/share/elasticsearch/data

  kibana:
    container_name: sample_crud_app_kibana
    image: docker.elastic.co/kibana/kibana:8.7.1
    ports:
      - "5601:5601"
    networks:
      - host
    depends_on:
      - elasticsearch
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    volumes:
      - samplecrudaspnet-data:/usr/share/kibana/data

  prometheus:
    container_name: sample_crud_app_prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - samplecrudaspnet-data:/usr/share/prometheus/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - host

  grafana:
    container_name: sample_crud_app_grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/datasource/:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards
      - samplecrudaspnet-data:/usr/share/grafana/data
    networks:
      - host

  postgres:
    container_name: sample_crud_app_postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: admin
      POSTGRES_DB: sample_crud_db
    volumes:
      - ./postgres/context.sql:/docker-entrypoint-initdb.d/context.sql
      - ./postgres//postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
      - samplecrudaspnet-data:/usr/share/postgres/data
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    networks:
      - host
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'

  redis:
    container_name: sample_crud_app_redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - host
    volumes:
      - samplecrudaspnet-data:/usr/share/redis/data
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'

  samplecrudapi_01: &samplecrudapi
    container_name: samplecrudapi_01
    image: samplecrudapi
    build:
      context: ../app/src
      dockerfile: .
    ports:
      - "5261:80"
    expose:
      - "80"
    depends_on:
      - elasticsearch
      - postgres
    restart: on-failure:10
    environment:
      - DBHOST=Server=sample_crud_app_postgres;Port=5432;Database=sample_crud_db;Username=admin;Password=postgres
      - ELASTICSEARCH_URL=http://elasticsearch:9200/
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - samplecrudaspnet-data:/usr/share/samplecrudapi/data
    networks:
      - host
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'

  samplecrudapi_02:
    <<: *samplecrudapi
    container_name: samplecrudapi_02
    ports:
      - "5262:80"

  nginx:
    container_name: sample_crud_app_nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - samplecrudaspnet-data:/usr/share/nginx/data
    depends_on:
      - samplecrudapi_01
      - samplecrudapi_02
    ports:
      - "9999:9999"
    networks:
      - host
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

networks:
  host:
    driver: bridge

volumes:
  samplecrudaspnet-data:
