version: '3.2'

services:
  sample_crud_app_web:
    image: ${DOCKER_REGISTRY-}app
    container_name: sample_crud
    build:
        context: ../app
        dockerfile: .
    ports:
      - "5261:80"
    depends_on:
      - sample_crud_app_db
    restart: always
    networks:
      - host
    environment: 
        - DBHOST=database
        - ASPNETCORE_ENVIRONMENT=Development
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'
      
  sample_crud_app_db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: admin
      POSTGRES_DB: sample_crud_db
    volumes:
      - ./db/context.sql:/docker-entrypoint-initdb.d/context.sql
    networks:
      - host
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'

  sample_crud_app_prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - host
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'

  sample_crud_app_grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/datasource:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
    depends_on:
      - sample_crud_app_prometheus
    networks:
      - host

  sample_crud_app_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - host

  sample_crud_app_kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - sample_crud_app_elasticsearch
    networks:
      - host
          
networks:
  host:
    driver: bridge
