# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  samplecrudapi:
    image: samplecrudapi
    build:
      context: .
      dockerfile: app/src/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5050:5050
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DBHOST=Server=db;Port=5432;Database=sample_crud_db;Username=admin;Password=postgres
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5431:5431"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: admin
      POSTGRES_DB: sample_crud_db
    volumes:
      - ./db/context.sql:/docker-entrypoint-initdb.d/context.sql