# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  postgres:
    container_name: postgres_debug
    image: postgres:16.1-alpine
    restart: always
    ports:
      - "5433:5432"
    # networks:
    #   - host
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: admin
      POSTGRES_DB: sample_crud_db
    volumes:
      - ../../infra/postgres/context.sql:/docker-entrypoint-initdb.d/context.sql
      - elasticsearch-debug-data:/usr/share/postgres/data

volumes:
  elasticsearch-debug-data:

networks:
  host:
    driver: bridge