version: '3.8'

services:
  postgres:
    container_name: sample_crud_app_postgres_debug
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    networks:
      - host
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: admin
      POSTGRES_DB: sample_crud_db
    volumes:
      - ../../infra/postgres/context.sql:/docker-entrypoint-initdb.d/context.sql
      - samplecrudaspnet-debug-data:/usr/share/postgres/data

  redis:
    container_name: sample_crud_app_redis_debug
    image: redis
    ports:
      - "6379:6379"
    networks:
      - host
    volumes:
      - ../../infra/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - samplecrudaspnet-debug-data:/usr/share/redis/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  samplecrudaspnet-debug-data:

networks:
  host:
    driver: bridge