# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  postgres:
    container_name: sample_crud_app_postgres_debug
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    networks:
      - host
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: admin
      POSTGRES_DB: sample_crud_db
    volumes:
      - ../../infra/postgres/context.sql:/docker-entrypoint-initdb.d/context.sql
      - samplecrudaspnet-debug-data:/usr/share/postgres/data

  redis:
    container_name: sample_crud_app_redis_debug
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - host
    volumes:
      - samplecrudaspnet-debug-data:/usr/share/redis/data

volumes:
  samplecrudaspnet-debug-data:

networks:
  host:
    driver: bridge