# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  sample_crud_app_elasticsearch_debug:
    container_name: elasticsearch_debug
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - node.name=elasticsearch
      - cluster.name=docker-elasticsearch
    volumes:
      - elasticsearch-debug-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - host

  sample_crud_app_kibana_debuger:
    container_name: kibana_debug
    image: docker.elastic.co/kibana/kibana:8.7.1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch_debug:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch_debug:9200
    volumes:
      - elasticsearch-debug-data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    depends_on:
      - sample_crud_app_elasticsearch_debug
    networks:
      - host

  sample_crud_app_db_debug:
    container_name: postgres_debug
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: admin
      POSTGRES_DB: sample_crud_db
    volumes:
      - ../../infra/db/context.sql:/docker-entrypoint-initdb.d/context.sql
      - elasticsearch-debug-data:/usr/share/postgres/data
    networks:
      - host


networks:
  host:
    driver: bridge

volumes:
  elasticsearch-debug-data:
