# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: 'sample_crud_app_web'
    scrape_interval: 5s
    static_configs:
      - targets: ["samplecrudapi_01", "samplecrudapi_02"]